services:
  server:
    build:
      context: .
      target: dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${SERVER_DEBUG_PORT}:${SERVER_DEBUG_PORT}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
  db:
    image: postgres
    restart: always
    user: ${POSTGRES_USER}
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
volumes:
  db-data:
